### PR TITLE
Expose SPL convergence parameters

### PR DESCRIPTION
**Pull request by jeanbraun**
@benbovy

In response to our discussion on the GSS tolerance issue, I have (re)adjusted the modifications made during the previous pull request and merge.

I have added a routine to the api and context to allow for the setting of three parameters:
- a relative tolerance
- an absolute tolerance
- a maximum number of iterations
for the stream power law algorithm that requires Gauss-Siedel iterations to take into account sediment deposition (see Yuan et al, 2019)

As in the previous pull request, I have removed the print statement that warns about the number of iterations having reached the limit

I have also added a routine to the api and context to obtain on demand the number of iterations performed during the GSS iteration loop

### CODE REVIEW

**Comment by benbovy** [comment]
Thanks @jeanbraun ! 

Do you think the two new API routines are worth being added to the documentation? (`api.adoc`)

**Comment by benbovy** [comment]
> Do you think the two new API routines are worth being added to the documentation? (api.adoc)

I added it in the last commits. I also removed the old computation of tolerance (commented) code lines that were still there.

@jeanbraun I have another question about the default values chosen for the relative and absolute tolerance:

Before #50, the actual tolerance was computed like this: `tol=1.d-4*(maxval(abs(h)) + 1.d0)`

In this PR, it is computed using `tol=tol_rel*maxval(abs(h)) + tol_abs` where the default values are `tol_rel=1e-3` and `tol_abs=1e-3`.

So the actual "default" value of `tol` is changed in this pull-request. Are we ok with this or should we choose default `tol_rel` / `tol_abs` values so that `tol` is kept the same?

**Comment by jeanbraun** [comment]
@benbovy 
Many thanks for updating the documentation.
Regarding the default values, I thought the previous condition was `tol=1.d-3*(maxval(abs(h)) + 1.d0)`; sorry, my mistake. This means that, to be consistent with the previous version, we need to set the default values to 1.d-4 for both `tol_abs` and `tol_rel`. Thanks.

**Review by benbovy — APPROVED** [review]
Many thanks @jeanbraun.

**Pull request merged**
